import React from 'react'
import styled from 'styled-components';

const Container = styled.div`
    padding-right: 20px;
    li{
        color: #a1a1a1;
    }
    
`;
const Heading = styled.h2`
    color: #bababa;
`;
const I = styled.i`
    color: #a6a6a6;
`;
const P = styled.p`
    color: #a1a1a1;
`;
const Bold = styled.strong`
    font-size: 16px;
    color: #a6a6a6;
`;

const Strong = styled.strong`
    font-size: 18px;
    color: #a6a6a6;
`;

const Title = styled.h2`

`;

const PrivacyPolicy = () => {
    return (
        <Container>
            <Title>Privacy Policy</Title>
            <br /><br />
            <Heading>BeatStars Inc. Privacy Policy</Heading>
            <br />
            <I>Effective date: May 25, 2018</I>
            <br /><br />
            <P>BeatStars Inc. is committed to protecting your privacy online. We are also committed to providing you with the very best experience we can on our website. In order to enhance your experience at our site we gather certain personal information about you that helps us customize our content to your tastes and preferences. Please read the following policy to understand how your personal information will be treated as you make full use of our website.</P>
            <br />
            <P>BeatStars Inc. ("BeatStars", "us", "we", or "our") operates the BeatStars.com website, BeatStars mobile applications and other related websites and applications (the "Service").</P>
            <br />
            <P>This page informs you of our policies regarding the collection, use, and disclosure of personal data when you use our Service and the choices you have associated with that data.</P>
            <br />
            <P>We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.</P>
            <br />
            <Strong>Definitions</Strong>
            <br />
            <br />
            <Bold>Personal Data</Bold>
            <br />
            <P>Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</P>
            <br />
            <Bold>Usage Data</Bold>
            <br />
            <P>Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</P>
            <br />
            <Bold>Cookies</Bold>
            <br />
            <P>Cookies are small pieces of data stored on a User's device.</P>
            <br />
            <Bold>Data Controller</Bold>
            <br />
            <P>Data Controller means a person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed.</P>
            <br />
            <P>For the purpose of this Privacy Policy, we are a Data Controller of your data.</P>
            <br />
            <Bold>Data Processor (or Service Providers)</Bold>
            <br />
            <P>Data Processor (or Service Provider) means any person (other than an employee of the Data Controller) who processes the data on behalf of the Data Controller.</P>

            <P>We may use the services of various Service Providers in order to process your data more effectively.</P>
            <br />
            <Bold>Data Subject</Bold>
            <br />
            <P>Data Subject is any living individual who is the subject of Personal Data.</P>
            <br />
            <Bold>User</Bold>
            <br />
            <P>The User is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.</P>
            <br />
            <Bold>Information Collection and Use</Bold>
            <br />
            <P>We collect several different types of information for various purposes to provide and improve our Service to you.</P>
            <br />
            <Strong>Types of Data Collected</Strong>
            <br />
            <br />
            <Bold>Personal Data</Bold>
            <br />
            <P>While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:</P>
            <br />
            <ul>
                <li>Email address</li>
                <li>First name and last name</li>
                <li>Phone number</li>
                <li>Address, State, Province, ZIP/Postal code, City</li>
                <li>Cookies and Usage Data</li>
            </ul>
            <br />
            <P>We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or instructions provided in any email we send or by contacting us.</P>

            <br />
            <Bold>Usage Data</Bold>
            <br />
            <P>We may also collect information that your browser sends whenever you visit our Service or when you access the Service by or through a mobile device ("Usage Data").</P>
            <br />
            <P>This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</P>
            <br />
            <P>When you access the Service by or through a mobile device, this Usage Data may include information such as the type of mobile device you use, your mobile device unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, unique device identifiers and other diagnostic data.</P>
            <br />

            <Bold>Location Data</Bold>
            <br />
            <P>We may use and store information about your location if you give us permission to do so ("Location Data"). We use this data to provide features of our Service, to improve and customize our Service.</P>
            <br />
            <P>You can enable or disable location services when you use our Service at any time, through your device settings.</P>

            <br />
            <Bold>Tracking Cookies Data</Bold>
            <br />
            <P>We use cookies and similar tracking technologies to track the activity on our Service and hold certain information.</P>
            <br />
            <P>Cookies are files with small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Tracking technologies also used are beacons, tags, and scripts to collect and track information and to improve and analyze our Service.</P>
            <br />
            <P>You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.</P>
            <br />
            <P>Examples of Cookies we use:</P>
            <br />
            <ul>
                <li><Bold>Session Cookies. </Bold>We use Session Cookies to operate our Service.</li>
                <li><Bold>Preference Cookies. </Bold>We use Preference Cookies to remember your preferences and various settings.</li>
                <li><Bold>Security Cookies. </Bold>We use Security Cookies for security purposes.</li>
            </ul>
            <br />

            <Bold>Use of Data</Bold>
            <br />
            <P>Our primary goal in collecting personal information is to provide you, the user, with a customized experience on our website. We use the collected data for various purposes including:</P>
            <br />
            <ul>
                <li>To provide and maintain our Service</li>
                <li>To notify you about changes to our Service or updates to our website</li>
                <li>To allow you to participate in interactive features of our Service when you choose to do so</li>
                <li>To provide customer support</li>
                <li>To gather analysis or valuable information so that we can improve our Service</li>
                <li>To monitor the usage of our Service, estimate the size of our audience and measure certain traffic patterns</li>
                <li>To detect, prevent and address technical issues</li>
                <li>To provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information</li>
                <li>To provide such capabilities as personalization services, interactive communications, online shopping, and personalized communication between you and the artists you prefer.</li>
                <li>To track the progress and number of entries in our promotions and contests</li>
                <li>To track visits to and business conducted at our online store</li>
                <li>To contact you on behalf of certain artists, other third parties, deliver targeted advertisements that may be of interest to you and information regarding special events at BeatStars.</li>
            </ul>
            <P>In addition, if we feel that a user abuses the BeatStars.com site in any way, we reserve the right to share certain information with third parties. Abuses include (but are not limited to) possible copyright infringement, possible libel and slander, possible credit card fraud.</P>

            <br />
            <Bold>Sharing of Data</Bold>
            <br />
            <P>BeatStars does not sell, rent, or trade your personal information with others. However, when one or more of our business partners co-sponsor a service, promotion and/or contest, we may share some or all of the information collected in connection with such service, promotion or contest with the co-sponsor(s). If you do not want your information to be shared, you will be able to choose not to allow the transfer by not using or signing up for that particular service, promotion or contest.</P>
            <br />
            <P>In addition, when you make a purchase through our online store, or sign up to receive promotional items from us, we may share some of your personal information with third parties helping us to complete your transaction or send you the items you signed up to receive. When we share your information with such third parties, we will work to ensure that only the information necessary to complete your transaction is disclosed. This privacy policy does not apply to such third parties.</P>
            <br />

            <Bold>Social Media</Bold>
            <br />
            <P>If you share our content through social media, for example by liking us on Facebook, following or tweeting about us on Twitter, or giving us a '+1' via Google Plus, those social networks will record that you have done so and may set a cookie for this purpose.</P>
            <br />
            <P>In some cases, where a page on our website includes content from a social network, such as a Twitter feed, or Facebook comments box, those services may set a cookie even where you do not click a button.  As is the case for all cookies, we cannot access those set by social networks, just as those social networks cannot access cookies we set ourselves.</P>
            <br />

            <Bold>Third Party Platform Advertising</Bold>
            <br />
            <P>We may share your information with third party platform providers (such as Facebook, Google, Twitter and Datacrushers) to serve targeted advertising/content to you via the relevant third-party platform based on your profile/interests. Your information is used by the third-party platform provider to identify your account and serve advertisements to you.</P>
            <br />

            <Bold>Facebook Conversion Tracking Pixel</Bold>
            <br />
            <P>Our website utilizes the Conversion Tracking Pixel service of Facebook. This tool allows us to follow the actions of users after they are redirected to a provider's website by clicking on a Facebook advertisement. We are thus able to record the efficiency of Facebook advertisements for statistical and market research purposes. The collected data remain anonymous and we cannot see the personal data of any individual user, however the collected data is saved and processed by Facebook. Facebook is able to connect this data with your Facebook account and the data is used for their own advertising purposes in accordance with their policy found under: <a href='https://www.facebook.com/about/privacy'>https://www.facebook.com/about/privacy</a>. Please click here if you would like to revoke your permission: <a href='https://www.facebook.com/ads/website_custom_audiences/'>https://www.facebook.com/ads/website_custom_audiences/</a>.</P>
            <br />


            <Bold>Datacrushers</Bold>
            <br />
            <P>Datacrushers is a revenue discovery platform and global leader in site-wide revenue, shopping cart abandonment recovery, and acceleration. Shopping cart data and email addresses are shared with the BeatStars producers that have opted in for the service. BeatStars producers are bound by their terms and conditions located at: <a href='https://www.datacrushers.com/terms-and-conditions'>https://www.datacrushers.com/terms-and-conditions</a>.</P>
            <br />


            <Bold>Retention of Data</Bold>
            <br />
            <P>We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</P>
            <br />
            <P>We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.</P>
            <br />

            <Bold>Transfer of Data</Bold>
            <br />
            <P>Your information, including Personal Data, may be transferred to - and maintained on - computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from your jurisdiction.</P>
            <br />
            <P>If you are located outside United States and choose to provide information to us, please note that we transfer the data, including Personal Data, to United States and process it there.</P>
            <br />
            <P>Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</P>
            <br />
            <P>BeatStars will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.</P>
            <br />

            <Bold>Disclosure of Data</Bold>
            <br />
            <br />
            <Bold>Business Transaction</Bold>
            <br />
            <P>If BeatStars Inc. is involved in a merger, acquisition or asset sale, your Personal Data may be transferred. We will provide notice before your Personal Data is transferred and becomes subject to a different Privacy Policy.</P>
            <br />
            <Bold>Disclosure for Law Enforcement</Bold>
            <br />
            <P>Under certain circumstances, BeatStars Inc. may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</P>
            <br />
            <Bold>Legal Requirements</Bold>
            <br />
            <P>BeatStars Inc. may disclose your Personal Data in the good faith belief that such action is necessary to:</P>
            <ul>
                <li>To comply with a legal obligation</li>
                <li>To protect and defend the rights or property of BeatStars Inc.</li>
                <li>To prevent or investigate possible wrongdoing in connection with the Service</li>
                <li>To protect the personal safety of users of the Service or the public</li>
                <li>To protect against legal liability</li>
            </ul>

            <br />
            <Bold>Security of Data</Bold>
            <br />
            <P>The security of your data is important to us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</P>
            <br />
            <Bold>"Do Not Track" Signals</Bold>
            <br />
            <P>We do not support Do Not Track ("DNT"). Do Not Track is a preference you can set in your web browser to inform websites that you do not want to be tracked.</P>
            <br />
            <P>You can enable or disable Do Not Track by visiting the Preferences or Settings page of your web browser.</P>
            <br />
            <Bold>Your Rights</Bold>
            <br />
            <P>BeatStars Inc. aims to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.</P>
            <br />
            <P>Whenever made possible, you can update your Personal Data directly within your account settings section. If you are unable to change your Personal Data, please contact us to make the required changes.</P>
            <br />
            <P>If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems, please contact us.</P>
            <br />
            <P>In certain circumstances, you have the right:</P>
            <br />
            <ul>
                <li>To access and receive a copy of the Personal Data we hold about you</li>
                <li>To rectify any Personal Data held about you that is inaccurate</li>
                <li>To request the deletion of Personal Data held about you</li>
            </ul>
            <br />
            <P>You have the right to data portability for the information you provide to BeatStars Inc.. You can request to obtain a copy of your Personal Data in a commonly used electronic format so that you can manage and move it.</P>
            <br />
            <P>Please note that we may ask you to verify your identity before responding to such requests.</P>

            <br />
            <Bold>Service Providers</Bold>
            <br />
            <P>We may employ third party companies and individuals to facilitate our Service ("Service Providers"), to provide the Service on our behalf, to perform Service-related services or to assist us in analyzing how our Service is used.</P>
            <br />
            <P>These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.</P>
            <br />
            <Bold>Analytics</Bold>
            <br />
            <P>We may use third-party Service Providers to monitor and analyze the use of our Service.</P>
            <br />
            <Bold>Google Analytics</Bold>
            <br />
            <P>Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualize and personalize the ads of its own advertising network.</P>
            <br />
            <P>For more information on the privacy practices of Google, please visit the Google Privacy Terms web page: <a href='http://www.google.com/intl/en/policies/privacy/'>http://www.google.com/intl/en/policies/privacy/</a></P>
            <br />

            <Bold>Payments</Bold>
            <br />
            <P>We may provide paid products and/or services within the Service. In that case, we use third-party services for payment processing (e.g. payment processors).</P>
            <br />
            <P>We will not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, Mastercard, American Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information.</P>
            <br />
            <P>The payment processors we work with are:</P>
            <br />


            <Bold>PayPal or Braintree</Bold>
            <br />
            <P>Their Privacy Policy can be viewed at</P>
            <P><a href='https://www.paypal.com/webapps/mpp/ua/privacy-full'>https://www.paypal.com/webapps/mpp/ua/privacy-full</a></P>
            <br />
            <Bold>Stripe</Bold>
            <br />
            <P>Their Privacy Policy can be viewed at <a href='https://stripe.com/us/privacy'>https://stripe.com/us/privacy</a></P>
            <br />

            <Bold>Links to Other Websites</Bold>
            <br />
            <P>Our Service may contain links to other websites that are not operated by us. If you click on a third-party link, you will be directed to that third party's website. We strongly advise you to review the Privacy Policy of every site you visit.</P>
            <br />
            <P>We have no control over and assume no responsibility for the content, privacy policies or practices of any third-party websites or services.</P>
            <br />

            <Bold>Children's Privacy</Bold>
            <br />
            <P>Our Service does not address anyone under the age of 18 ("Children").</P>
            <br />
            <P>We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your Children has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.</P>
            <br />


            <Bold>Changes to This Privacy Policy</Bold>
            <br />
            <P>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</P>
            <br />
            <P>We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update the "effective date" at the top of this Privacy Policy.</P>
            <br />
            <P>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</P>
            <br />

            <Bold>Contact Us</Bold>
            <pr />
            <P>If you have any questions about this Privacy Policy, please contact us:</P>
            <br />
            <ul>
                <li>By email: sales@beatstars.com</li>
                <li>By visiting this page on our website: <a href='By visiting this page on our website: '>By visiting this page on our website: </a></li>
            </ul>
            <br />
            <Bold>Previous Privacy Policies</Bold>
            <br />
            <ul>
                <li><a href='Privacy Policy 2015/06/01'>Privacy Policy 2015/06/01</a></li>
            </ul>
            <br />
            <br />
            <br />
            <br />


        </Container>
    )
}

export default PrivacyPolicy